name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
        with:
          go-version: 1.21.3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@74483a38d39275f33fcff5f35b679b5ca4a26a99 #v2.22.5
        with:
          languages: go
      - name: Run build
        run: go build github.com/lonegunmanb/yorbox
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@74483a38d39275f33fcff5f35b679b5ca4a26a99 #v2.22.5
      - name: Run tests
        run: go test -v github.com/lonegunmanb/yorbox/...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc #v3.7.0
        with:
          version:
            v1.53
      - name: Run Gosec Security Scanner
        uses: securego/gosec@55d79496019a560e16e73e1948dee20a1fad631a #v2.18.2
        if: runner.os == 'Linux'